// <auto-generated />
using System;
using BrasilApiIntegration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrasilApiIntegration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BrasilApiIntegration.Data.Entities.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Message");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Log", (string)null);
                });

            modelBuilder.Entity("BrasilApiIntegration.Data.Entities.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime")
                        .HasColumnName("AtualizadoEm");

                    b.Property<string>("CodigoIcao")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CodigoIcao");

                    b.Property<string>("Condicao")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Condicao");

                    b.Property<string>("CondicaoDescricao")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CondicaoDescricao");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DirecaoVento")
                        .HasColumnType("int")
                        .HasColumnName("DirecaoVento");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PressaoAtmosferica")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PressaoAtmosferica");

                    b.Property<int>("Temp")
                        .HasColumnType("int")
                        .HasColumnName("Temp");

                    b.Property<int>("Umidade")
                        .HasColumnType("int")
                        .HasColumnName("Umidade");

                    b.Property<int>("Vento")
                        .HasColumnType("int")
                        .HasColumnName("Vento");

                    b.Property<string>("Visibilidade")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Visibilidade");

                    b.HasKey("Id");

                    b.ToTable("Weather", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
